backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "images"

collections:
  - name: "roster"
    label: "Состав команды"
    folder: "content/roster"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Имя и Фамилия", name: "title", widget: "string" }
      - { label: "Номер игрока", name: "number", widget: "string" }
      - { label: "Позиция (Роль)", name: "role", widget: "string" }
      - { label: "Рост (см)", name: "height", widget: "string" }
      - { label: "Высота съема (см)", name: "spike", widget: "string" }
      - { label: "Фотография", name: "photo", widget: "image" }

  - name: "matches"
    label: "Календарь матчей"
    folder: "content/matches"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Соперник", name: "opponent", widget: "string" }
      - { label: "Дата и время", name: "datetime", widget: "string" }
      - { label: "Место проведения", name: "location", widget: "string" }
      - { label: "Статус матча", name: "status", widget: "select", options: ["Предстоящий", "Завершен"] }
